RiverMeThis/Controllers/FloatTripsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RiverMeThis.Data;
using RiverMeThis.Models;
using RiverMeThis.Models.FloatTripViewModels;

namespace RiverMeThis.Controllers
{
    public class FloatTripsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;
        public FloatTripsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: FloatTrips
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var applicationDbContext = _context.FloatTrip.Include(f => f.Device).Include(f => f.PutInAP).Include(f => f.River).Include(f => f.Sherpa).Include(f => f.TakeOutAP).Include(f => f.User).OrderBy(f => f.Date).Where(r => r.UserId == user.Id);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: FloatTrips/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var floatTrip = await _context.FloatTrip
                .Include(f => f.Device)
                .Include(f => f.PutInAP)
                .Include(f => f.River)
                .Include(f => f.Sherpa)
                .Include(f => f.TakeOutAP)
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.FloatTripId == id);
            if (floatTrip == null)
            {
                return NotFound();
            }

            return View(floatTrip);
        }

        // GET: FloatTrips/Create
        public IActionResult Create()
        {
            FloatTripCreateViewModel ViewModel = new FloatTripCreateViewModel();

            ViewModel.rivers = _context.River.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.RiverId.ToString()
            }
          ).ToList();

            ViewModel.rivers.Insert(0, new SelectListItem() { Value = "0", Text = "--Select A River--" });

            ViewModel.devices = _context.Device.Select(d => new SelectListItem
            {
                Text = d.Type,
                Value = d.DeviceId.ToString()
            }
            ).ToList();

            ViewModel.devices.Insert(0, new SelectListItem() { Value = "0", Text = "--Select A Device--" });

            return View(ViewModel);
        }

        // POST: FloatTrips/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Date,NumberOfFloaters,UserId,RiverId,DeviceId")] FloatTrip floatTrip)
        {
            ModelState.Remove("floatTrip.User");
            ModelState.Remove("floatTrip.UserId");

            FloatTripCreateViewModel ViewModel = new FloatTripCreateViewModel();
            if (ModelState.IsValid)
            {
                //Check User's Id
                var user = await GetCurrentUserAsync();
                floatTrip.UserId = user.Id;
                _context.Add(floatTrip);
                await _context.SaveChangesAsync();
                return RedirectToAction("PicAPs", new { id = floatTrip.FloatTripId });
            }

            ViewModel.rivers = _context.River.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.RiverId.ToString()
            }).ToList();

            ViewModel.devices = _context.Device.Select(d => new SelectListItem
            {
                Text = d.Type,
                Value = d.DeviceId.ToString()
            }).ToList();

            return View(ViewModel);
        }

        // GET: FloatTrips/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var floatTrip = await _context.FloatTrip
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.FloatTripId == id);

            if (floatTrip == null)
            {
                return NotFound();
            }

            ViewData["DeviceId"] = new SelectList(_context.Device, "DeviceId", "Type", floatTrip.DeviceId);
            ViewData["PutInAPId"] = new SelectList(_context.AccessPoint, "AccessPointId", "AccessPointId", floatTrip.PutInAPId);
            ViewData["RiverId"] = new SelectList(_context.River, "RiverId", "RiverId", floatTrip.RiverId);
            ViewData["SherpaId"] = new SelectList(_context.Sherpa, "SherpaId", "FirstName", floatTrip.SherpaId);
            ViewData["TakeOutAPId"] = new SelectList(_context.AccessPoint, "AccessPointId", "AccessPointId", floatTrip.TakeOutAPId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", floatTrip.UserId);
            return View(floatTrip);
        }

        // POST: FloatTrips/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FloatTripId,Title,Date,Distance,NumberOfFloaters,Duration,Notes,Rating,PicPath,NeedASherpa,UserId,User,RiverId,PutInAPId,TakeOutAPId,DeviceId,SherpaId")] FloatTrip floatTrip)
        {

            if (id != floatTrip.FloatTripId)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            //{
            try
            {
                _context.Update(floatTrip);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FloatTripExists(floatTrip.FloatTripId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
        
            return RedirectToAction(nameof(Index));

            ViewData["DeviceId"] = new SelectList(_context.Device, "DeviceId", "Type", floatTrip.DeviceId);
            ViewData["PutInAPId"] = new SelectList(_context.AccessPoint, "AccessPointId", "AccessPointId", floatTrip.PutInAPId);
            ViewData["RiverId"] = new SelectList(_context.River, "RiverId", "RiverId", floatTrip.RiverId);
            ViewData["SherpaId"] = new SelectList(_context.Sherpa, "SherpaId", "FirstName", floatTrip.SherpaId);
            ViewData["TakeOutAPId"] = new SelectList(_context.AccessPoint, "AccessPointId", "AccessPointId", floatTrip.TakeOutAPId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", floatTrip.UserId);
            return View(floatTrip);
        }

        // GET: FloatTrips/PicAPs/5
        public async Task<IActionResult> PicAPs(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var floatTrip = await _context.FloatTrip
                .Include(r => r.River)
                .ThenInclude(ap => ap.AvailableAPs)
                .FirstOrDefaultAsync(m => m.FloatTripId == id);
            
            if (floatTrip == null)
            {
                return NotFound();
            }
                       
            AccessPointsPickViewModel ViewModel = new AccessPointsPickViewModel();
            ViewModel.riverId = floatTrip.River.RiverId;
            //ViewModel.floatTrip.User = floatTrip.User;
            
            ViewModel.putIns = floatTrip.River.AvailableAPs.Select(p => new SelectListItem
            {
                Text = p.Name,
                Value = p.AccessPointId.ToString()
            }
            ).ToList();

            ViewModel.putIns.Insert(0, new SelectListItem() { Value = "0", Text = "--Select A Put-In--" });

            ViewModel.takeOuts = floatTrip.River.AvailableAPs.Select(t => new SelectListItem
            {
                Text = t.Name,
                Value = t.AccessPointId.ToString()
            }
            ).ToList();

            ViewModel.takeOuts.Insert(0, new SelectListItem() { Value = "0", Text = "--Select A Take-Out--" });

            //This ViewModel only has PutInAPId and TakeOutAPId
            return View(ViewModel);
        }
    

        // POST: FloatTrips/PicAPs/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        //The following line with Type FloatTrip floatTrip is what is coming in from the Get model above
        public async Task<IActionResult> PicAPs(int id, [Bind("User, UserId, Title,RiverId,PutInAPId,TakeOutAPId,")] FloatTrip floatTrip)
        {
            //Don't need this next line because I am IN the new FloatTrip I'm creating - comes from the int id in the call above

            //if (id != floatTrip.FloatTripId)
            //{
            //    return NotFound();
            //}

            //New ThisfloatTrip variable to get the information on this floattrip from the database
           var ThisfloatTrip = await _context.FloatTrip
               .FirstOrDefaultAsync(f => f.FloatTripId == id);

RiverMeThis/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RiverMeThis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="bower_components/css-ripple-effect/dist/ripple.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Akronim&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Merienda&display=swap" rel="stylesheet">

</head>
<body style="font-family:Merienda;">
    <header>
        <nav class="navbar-expand-sm navbar-toggleable-sm bg-navbar box-shadow mb-3" style="padding:0; width:100vw;">
            <div class="container" style="margin-left:1em;">
                <a class="navbar-brand ripple" asp-area="" asp-controller="Home" asp-action="Index" style="padding:0;font-size: 40px">River Me This...</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" style="width: 85vw;">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" style="margin-left:5em;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item" style="margin-left:2em;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="FloatTrips" asp-action="Index">Floats</a>
                            </li>
                            <li class="nav-item" style="margin-left:2em;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">How You Doin'?</a>
                            </li>
                            @*<li class="nav-item" style="margin-left:2em; margin-right:7.5em;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Details">View Profile</a>
                            </li>*@

                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - RiverMeThis - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>